=== Roppest/pletoraDeLetras/XSL/catalogoLibrosTipo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="catalogoLibros" type="tipoCatalogoLibros"/>
	
	<xs:complexType name="tipoCatalogoLibros">	
		<xs:sequence>
			<xs:element name="libro" type="tipoLibro" minOccurs="1" maxOccurs="100"/>
		</xs:sequence>
		
	</xs:complexType>
	<xs:complexType name="tipoLibro">
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="resumen" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="tema" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="idioma" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="anioPublicacion" minOccurs="1" maxOccurs="1">
			  	<xs:simpleType>
            		<xs:restriction base="xs:string">
            		<xs:pattern value="[0-9][0-9][0-9][0-9]"/>
            		</xs:restriction>
          		</xs:simpleType>
			</xs:element>
			<xs:element name="editorial" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ciudad" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="paisPublicacion" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="fotoPortada" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="autor" minOccurs="1" maxOccurs="10">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z][0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>

		<xs:attribute name="isbn">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== Roppest/pletoraDeLetras/XSL/catalogoLibros.xml
<?xml version="1.0"?>
<catalogoLibros xsi:noNamespaceSchemaLocation="catalogoLibrosTipo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<libro isbn="9788535211856">
		<titulo>Computer Networks</titulo>
		<resumen>Appropriate for courses titled Computer Networking or Introduction to Networking at both the undergraduate and graduate level in Computer Science, Electrical Engineering, CIS, MIS, and Business Departments. </resumen>
		<tema>Redes de Computadoras</tema>
		<idioma>Ingles</idioma>
		<anioPublicacion>1981</anioPublicacion>
		<editorial>Pearson</editorial>
		<ciudad>California</ciudad>
		<paisPublicacion>EUA</paisPublicacion>
		<fotoPortada>networks.jpg</fotoPortada>
		<autores>T401</autores>
	</libro>
	<libro isbn="9788871923666">
		<titulo>Sistemas Distribuidos</titulo>
		<resumen>En esta nueva edición se agregó un capítulo independiente sobre arquitecturas para reflejar el progreso que se ha dado en la organización de sistemas distribuidos. Otra diferencia importante es que ahora existe mucho más material acerca de sistemas descentralizados, en especial sobre computación de igual a igual (peer-to-peer)</resumen>
		<tema>Sistemas Distribuidos</tema>
		<idioma>Espaniol<idioma>
		<anioPublicacion>2007</anioPublicacion>
		<editorial>Pearson</editorial>
		<ciudad>California</ciudad>
		<paisPublicacion>EUA<paisPublicacion>
		<fotoPortada>sistemasDistribuidos.jpg</fotoPortada>
		<autores>T401,M401</autores>
	</libro>
	<libro isbn="9781259252983">
                <titulo>Database System Concepts</titulo>
                <resumen>Database System Concepts by Silberschatz, Korth and Sudarshan is now in its 6th edition and is one of the cornerstone texts of database education.</resumen>
                <tema>Bases de Datos</tema>
                <idioma>Ingles<idioma>
                <anioPublicacion>2007</anioPublicacion>
                <editorial>MCGraw Hill</editorial>
                <ciudad>California</ciudad>
                <paisPublicacion>EUA<paisPublicacion>
                <fotoPortada>database.jpg</fotoPortada>
                <autores>A001,K002</autores>
        </libro>
        <libro isbn="9781548955465">
                <titulo>JavaScript and JQuery</titulo>
                <resumen>JavaScript was written to give readers an accurate, concise examination of JavaScript objects and their supporting nuances, such as complex values, primitive values, scope, inheritance, the head object, and more.</resumen>
                <tema>Programacion Web</tema>
                <idioma>Ingles<idioma>
                <anioPublicacion>2017</anioPublicacion>
                <editorial>Create Space</editorial>
                <ciudad>Boston</ciudad>
                <paisPublicacion>EUA<paisPublicacion>
                <fotoPortada>jscript.jpg</fotoPortada>
                <autores>J223</autores>
        </libro>
</catalogoLibros>
